# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'wei.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName(_fromUtf8("Dialog"))
        Dialog.resize(903, 595)
        self.layoutWidget = QtGui.QWidget(Dialog)
        self.layoutWidget.setGeometry(QtCore.QRect(71, 31, 675, 464))
        self.layoutWidget.setObjectName(_fromUtf8("layoutWidget"))
        self.gridLayout_2 = QtGui.QGridLayout(self.layoutWidget)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.verticalLayout_37 = QtGui.QVBoxLayout()
        self.verticalLayout_37.setObjectName(_fromUtf8("verticalLayout_37"))
        self.gridLayout = QtGui.QGridLayout()
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.verticalLayout_10 = QtGui.QVBoxLayout()
        self.verticalLayout_10.setObjectName(_fromUtf8("verticalLayout_10"))
        self.verticalLayout_9 = QtGui.QVBoxLayout()
        self.verticalLayout_9.setObjectName(_fromUtf8("verticalLayout_9"))
        self.label_2 = QtGui.QLabel(self.layoutWidget)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.verticalLayout_9.addWidget(self.label_2)
        self.horizontalLayout_4 = QtGui.QHBoxLayout()
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.verticalLayout = QtGui.QVBoxLayout()
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.projectNameL = QtGui.QLabel(self.layoutWidget)
        self.projectNameL.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.projectNameL.setObjectName(_fromUtf8("projectNameL"))
        self.verticalLayout.addWidget(self.projectNameL)
        self.checkRecordNoL = QtGui.QLabel(self.layoutWidget)
        self.checkRecordNoL.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.checkRecordNoL.setObjectName(_fromUtf8("checkRecordNoL"))
        self.verticalLayout.addWidget(self.checkRecordNoL)
        self.checkNoL = QtGui.QLabel(self.layoutWidget)
        self.checkNoL.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.checkNoL.setObjectName(_fromUtf8("checkNoL"))
        self.verticalLayout.addWidget(self.checkNoL)
        self.horizontalLayout.addLayout(self.verticalLayout)
        self.verticalLayout_2 = QtGui.QVBoxLayout()
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.projectNameLE = QtGui.QLineEdit(self.layoutWidget)
        self.projectNameLE.setObjectName(_fromUtf8("projectNameLE"))
        self.verticalLayout_2.addWidget(self.projectNameLE)
        self.checkRecordNoLE = QtGui.QLineEdit(self.layoutWidget)
        self.checkRecordNoLE.setObjectName(_fromUtf8("checkRecordNoLE"))
        self.verticalLayout_2.addWidget(self.checkRecordNoLE)
        self.checkNoLE = QtGui.QLineEdit(self.layoutWidget)
        self.checkNoLE.setObjectName(_fromUtf8("checkNoLE"))
        self.verticalLayout_2.addWidget(self.checkNoLE)
        self.horizontalLayout.addLayout(self.verticalLayout_2)
        self.horizontalLayout_4.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.verticalLayout_3 = QtGui.QVBoxLayout()
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.checkprojectL = QtGui.QLabel(self.layoutWidget)
        self.checkprojectL.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.checkprojectL.setObjectName(_fromUtf8("checkprojectL"))
        self.verticalLayout_3.addWidget(self.checkprojectL)
        self.checkAccordL = QtGui.QLabel(self.layoutWidget)
        self.checkAccordL.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.checkAccordL.setObjectName(_fromUtf8("checkAccordL"))
        self.verticalLayout_3.addWidget(self.checkAccordL)
        self.checkCountL = QtGui.QLabel(self.layoutWidget)
        self.checkCountL.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.checkCountL.setObjectName(_fromUtf8("checkCountL"))
        self.verticalLayout_3.addWidget(self.checkCountL)
        self.horizontalLayout_2.addLayout(self.verticalLayout_3)
        self.verticalLayout_6 = QtGui.QVBoxLayout()
        self.verticalLayout_6.setObjectName(_fromUtf8("verticalLayout_6"))
        self.checkProjectLE = QtGui.QLineEdit(self.layoutWidget)
        self.checkProjectLE.setObjectName(_fromUtf8("checkProjectLE"))
        self.verticalLayout_6.addWidget(self.checkProjectLE)
        self.checkAccordLE = QtGui.QLineEdit(self.layoutWidget)
        self.checkAccordLE.setObjectName(_fromUtf8("checkAccordLE"))
        self.verticalLayout_6.addWidget(self.checkAccordLE)
        self.checkCountLE = QtGui.QLineEdit(self.layoutWidget)
        self.checkCountLE.setObjectName(_fromUtf8("checkCountLE"))
        self.verticalLayout_6.addWidget(self.checkCountLE)
        self.horizontalLayout_2.addLayout(self.verticalLayout_6)
        self.horizontalLayout_4.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.verticalLayout_7 = QtGui.QVBoxLayout()
        self.verticalLayout_7.setObjectName(_fromUtf8("verticalLayout_7"))
        self.piezometerNoL = QtGui.QLabel(self.layoutWidget)
        self.piezometerNoL.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.piezometerNoL.setObjectName(_fromUtf8("piezometerNoL"))
        self.verticalLayout_7.addWidget(self.piezometerNoL)
        self.dialgaugeNoL = QtGui.QLabel(self.layoutWidget)
        self.dialgaugeNoL.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.dialgaugeNoL.setObjectName(_fromUtf8("dialgaugeNoL"))
        self.verticalLayout_7.addWidget(self.dialgaugeNoL)
        self.loadL = QtGui.QLabel(self.layoutWidget)
        self.loadL.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.loadL.setObjectName(_fromUtf8("loadL"))
        self.verticalLayout_7.addWidget(self.loadL)
        self.horizontalLayout_3.addLayout(self.verticalLayout_7)
        self.verticalLayout_8 = QtGui.QVBoxLayout()
        self.verticalLayout_8.setObjectName(_fromUtf8("verticalLayout_8"))
        self.piezometerNoLE = QtGui.QLineEdit(self.layoutWidget)
        self.piezometerNoLE.setObjectName(_fromUtf8("piezometerNoLE"))
        self.verticalLayout_8.addWidget(self.piezometerNoLE)
        self.dialgaugeNoLE = QtGui.QLineEdit(self.layoutWidget)
        self.dialgaugeNoLE.setObjectName(_fromUtf8("dialgaugeNoLE"))
        self.verticalLayout_8.addWidget(self.dialgaugeNoLE)
        self.loadLE = QtGui.QLineEdit(self.layoutWidget)
        self.loadLE.setObjectName(_fromUtf8("loadLE"))
        self.verticalLayout_8.addWidget(self.loadLE)
        self.horizontalLayout_3.addLayout(self.verticalLayout_8)
        self.horizontalLayout_4.addLayout(self.horizontalLayout_3)
        self.verticalLayout_9.addLayout(self.horizontalLayout_4)
        self.verticalLayout_10.addLayout(self.verticalLayout_9)
        self.line = QtGui.QFrame(self.layoutWidget)
        self.line.setFrameShape(QtGui.QFrame.HLine)
        self.line.setFrameShadow(QtGui.QFrame.Sunken)
        self.line.setObjectName(_fromUtf8("line"))
        self.verticalLayout_10.addWidget(self.line)
        self.gridLayout.addLayout(self.verticalLayout_10, 0, 0, 1, 3)
        self.verticalLayout_36 = QtGui.QVBoxLayout()
        self.verticalLayout_36.setObjectName(_fromUtf8("verticalLayout_36"))
        self.verticalLayout_13 = QtGui.QVBoxLayout()
        self.verticalLayout_13.setObjectName(_fromUtf8("verticalLayout_13"))
        self.label_3 = QtGui.QLabel(self.layoutWidget)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.verticalLayout_13.addWidget(self.label_3)
        self.horizontalLayout_5 = QtGui.QHBoxLayout()
        self.horizontalLayout_5.setObjectName(_fromUtf8("horizontalLayout_5"))
        self.verticalLayout_11 = QtGui.QVBoxLayout()
        self.verticalLayout_11.setObjectName(_fromUtf8("verticalLayout_11"))
        self.monthL = QtGui.QLabel(self.layoutWidget)
        self.monthL.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.monthL.setObjectName(_fromUtf8("monthL"))
        self.verticalLayout_11.addWidget(self.monthL)
        self.dayL = QtGui.QLabel(self.layoutWidget)
        self.dayL.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.dayL.setObjectName(_fromUtf8("dayL"))
        self.verticalLayout_11.addWidget(self.dayL)
        self.hourL = QtGui.QLabel(self.layoutWidget)
        self.hourL.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.hourL.setObjectName(_fromUtf8("hourL"))
        self.verticalLayout_11.addWidget(self.hourL)
        self.minuteL = QtGui.QLabel(self.layoutWidget)
        self.minuteL.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.minuteL.setObjectName(_fromUtf8("minuteL"))
        self.verticalLayout_11.addWidget(self.minuteL)
        self.horizontalLayout_5.addLayout(self.verticalLayout_11)
        self.verticalLayout_12 = QtGui.QVBoxLayout()
        self.verticalLayout_12.setObjectName(_fromUtf8("verticalLayout_12"))
        self.monthLE = QtGui.QLineEdit(self.layoutWidget)
        self.monthLE.setObjectName(_fromUtf8("monthLE"))
        self.verticalLayout_12.addWidget(self.monthLE)
        self.dayLE = QtGui.QLineEdit(self.layoutWidget)
        self.dayLE.setObjectName(_fromUtf8("dayLE"))
        self.verticalLayout_12.addWidget(self.dayLE)
        self.hourLE = QtGui.QLineEdit(self.layoutWidget)
        self.hourLE.setObjectName(_fromUtf8("hourLE"))
        self.verticalLayout_12.addWidget(self.hourLE)
        self.minuteLE = QtGui.QLineEdit(self.layoutWidget)
        self.minuteLE.setObjectName(_fromUtf8("minuteLE"))
        self.verticalLayout_12.addWidget(self.minuteLE)
        self.horizontalLayout_5.addLayout(self.verticalLayout_12)
        self.verticalLayout_13.addLayout(self.horizontalLayout_5)
        self.verticalLayout_36.addLayout(self.verticalLayout_13)
        self.line_4 = QtGui.QFrame(self.layoutWidget)
        self.line_4.setFrameShape(QtGui.QFrame.HLine)
        self.line_4.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_4.setObjectName(_fromUtf8("line_4"))
        self.verticalLayout_36.addWidget(self.line_4)
        self.gridLayout.addLayout(self.verticalLayout_36, 1, 0, 1, 1)
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem, 1, 1, 1, 1)
        self.horizontalLayout_18 = QtGui.QHBoxLayout()
        self.horizontalLayout_18.setObjectName(_fromUtf8("horizontalLayout_18"))
        self.line_3 = QtGui.QFrame(self.layoutWidget)
        self.line_3.setFrameShape(QtGui.QFrame.VLine)
        self.line_3.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_3.setObjectName(_fromUtf8("line_3"))
        self.horizontalLayout_18.addWidget(self.line_3)
        self.verticalLayout_35 = QtGui.QVBoxLayout()
        self.verticalLayout_35.setObjectName(_fromUtf8("verticalLayout_35"))
        self.label_4 = QtGui.QLabel(self.layoutWidget)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.verticalLayout_35.addWidget(self.label_4)
        self.verticalLayout_34 = QtGui.QVBoxLayout()
        self.verticalLayout_34.setObjectName(_fromUtf8("verticalLayout_34"))
        self.horizontalLayout_12 = QtGui.QHBoxLayout()
        self.horizontalLayout_12.setObjectName(_fromUtf8("horizontalLayout_12"))
        self.verticalLayout_18 = QtGui.QVBoxLayout()
        self.verticalLayout_18.setObjectName(_fromUtf8("verticalLayout_18"))
        self.label_5 = QtGui.QLabel(self.layoutWidget)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.verticalLayout_18.addWidget(self.label_5)
        self.horizontalLayout_6 = QtGui.QHBoxLayout()
        self.horizontalLayout_6.setObjectName(_fromUtf8("horizontalLayout_6"))
        self.verticalLayout_14 = QtGui.QVBoxLayout()
        self.verticalLayout_14.setObjectName(_fromUtf8("verticalLayout_14"))
        self.fL = QtGui.QLabel(self.layoutWidget)
        self.fL.setObjectName(_fromUtf8("fL"))
        self.verticalLayout_14.addWidget(self.fL)
        self.gL = QtGui.QLabel(self.layoutWidget)
        self.gL.setObjectName(_fromUtf8("gL"))
        self.verticalLayout_14.addWidget(self.gL)
        self.horizontalLayout_6.addLayout(self.verticalLayout_14)
        self.verticalLayout_15 = QtGui.QVBoxLayout()
        self.verticalLayout_15.setObjectName(_fromUtf8("verticalLayout_15"))
        self.fLE = QtGui.QLineEdit(self.layoutWidget)
        self.fLE.setObjectName(_fromUtf8("fLE"))
        self.verticalLayout_15.addWidget(self.fLE)
        self.gLE = QtGui.QLineEdit(self.layoutWidget)
        self.gLE.setObjectName(_fromUtf8("gLE"))
        self.verticalLayout_15.addWidget(self.gLE)
        self.horizontalLayout_6.addLayout(self.verticalLayout_15)
        self.verticalLayout_18.addLayout(self.horizontalLayout_6)
        self.horizontalLayout_12.addLayout(self.verticalLayout_18)
        self.verticalLayout_21 = QtGui.QVBoxLayout()
        self.verticalLayout_21.setObjectName(_fromUtf8("verticalLayout_21"))
        self.label_6 = QtGui.QLabel(self.layoutWidget)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.verticalLayout_21.addWidget(self.label_6)
        self.horizontalLayout_7 = QtGui.QHBoxLayout()
        self.horizontalLayout_7.setObjectName(_fromUtf8("horizontalLayout_7"))
        self.verticalLayout_19 = QtGui.QVBoxLayout()
        self.verticalLayout_19.setObjectName(_fromUtf8("verticalLayout_19"))
        self.lL = QtGui.QLabel(self.layoutWidget)
        self.lL.setObjectName(_fromUtf8("lL"))
        self.verticalLayout_19.addWidget(self.lL)
        self.mL = QtGui.QLabel(self.layoutWidget)
        self.mL.setObjectName(_fromUtf8("mL"))
        self.verticalLayout_19.addWidget(self.mL)
        self.horizontalLayout_7.addLayout(self.verticalLayout_19)
        self.verticalLayout_20 = QtGui.QVBoxLayout()
        self.verticalLayout_20.setObjectName(_fromUtf8("verticalLayout_20"))
        self.lLE = QtGui.QLineEdit(self.layoutWidget)
        self.lLE.setObjectName(_fromUtf8("lLE"))
        self.verticalLayout_20.addWidget(self.lLE)
        self.mLE = QtGui.QLineEdit(self.layoutWidget)
        self.mLE.setObjectName(_fromUtf8("mLE"))
        self.verticalLayout_20.addWidget(self.mLE)
        self.horizontalLayout_7.addLayout(self.verticalLayout_20)
        self.verticalLayout_21.addLayout(self.horizontalLayout_7)
        self.horizontalLayout_12.addLayout(self.verticalLayout_21)
        self.verticalLayout_34.addLayout(self.horizontalLayout_12)
        self.line_5 = QtGui.QFrame(self.layoutWidget)
        self.line_5.setFrameShape(QtGui.QFrame.HLine)
        self.line_5.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_5.setObjectName(_fromUtf8("line_5"))
        self.verticalLayout_34.addWidget(self.line_5)
        self.horizontalLayout_15 = QtGui.QHBoxLayout()
        self.horizontalLayout_15.setObjectName(_fromUtf8("horizontalLayout_15"))
        self.verticalLayout_24 = QtGui.QVBoxLayout()
        self.verticalLayout_24.setObjectName(_fromUtf8("verticalLayout_24"))
        self.label_7 = QtGui.QLabel(self.layoutWidget)
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.verticalLayout_24.addWidget(self.label_7)
        self.horizontalLayout_8 = QtGui.QHBoxLayout()
        self.horizontalLayout_8.setObjectName(_fromUtf8("horizontalLayout_8"))
        self.verticalLayout_22 = QtGui.QVBoxLayout()
        self.verticalLayout_22.setObjectName(_fromUtf8("verticalLayout_22"))
        self.rL = QtGui.QLabel(self.layoutWidget)
        self.rL.setObjectName(_fromUtf8("rL"))
        self.verticalLayout_22.addWidget(self.rL)
        self.sL = QtGui.QLabel(self.layoutWidget)
        self.sL.setObjectName(_fromUtf8("sL"))
        self.verticalLayout_22.addWidget(self.sL)
        self.horizontalLayout_8.addLayout(self.verticalLayout_22)
        self.verticalLayout_23 = QtGui.QVBoxLayout()
        self.verticalLayout_23.setObjectName(_fromUtf8("verticalLayout_23"))
        self.rLE = QtGui.QLineEdit(self.layoutWidget)
        self.rLE.setObjectName(_fromUtf8("rLE"))
        self.verticalLayout_23.addWidget(self.rLE)
        self.sLE = QtGui.QLineEdit(self.layoutWidget)
        self.sLE.setObjectName(_fromUtf8("sLE"))
        self.verticalLayout_23.addWidget(self.sLE)
        self.horizontalLayout_8.addLayout(self.verticalLayout_23)
        self.verticalLayout_24.addLayout(self.horizontalLayout_8)
        self.horizontalLayout_15.addLayout(self.verticalLayout_24)
        self.verticalLayout_27 = QtGui.QVBoxLayout()
        self.verticalLayout_27.setObjectName(_fromUtf8("verticalLayout_27"))
        self.label_8 = QtGui.QLabel(self.layoutWidget)
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.verticalLayout_27.addWidget(self.label_8)
        self.horizontalLayout_9 = QtGui.QHBoxLayout()
        self.horizontalLayout_9.setObjectName(_fromUtf8("horizontalLayout_9"))
        self.verticalLayout_25 = QtGui.QVBoxLayout()
        self.verticalLayout_25.setObjectName(_fromUtf8("verticalLayout_25"))
        self.tL = QtGui.QLabel(self.layoutWidget)
        self.tL.setObjectName(_fromUtf8("tL"))
        self.verticalLayout_25.addWidget(self.tL)
        self.uL = QtGui.QLabel(self.layoutWidget)
        self.uL.setObjectName(_fromUtf8("uL"))
        self.verticalLayout_25.addWidget(self.uL)
        self.horizontalLayout_9.addLayout(self.verticalLayout_25)
        self.verticalLayout_26 = QtGui.QVBoxLayout()
        self.verticalLayout_26.setObjectName(_fromUtf8("verticalLayout_26"))
        self.tLE = QtGui.QLineEdit(self.layoutWidget)
        self.tLE.setObjectName(_fromUtf8("tLE"))
        self.verticalLayout_26.addWidget(self.tLE)
        self.uLE = QtGui.QLineEdit(self.layoutWidget)
        self.uLE.setObjectName(_fromUtf8("uLE"))
        self.verticalLayout_26.addWidget(self.uLE)
        self.horizontalLayout_9.addLayout(self.verticalLayout_26)
        self.verticalLayout_27.addLayout(self.horizontalLayout_9)
        self.horizontalLayout_15.addLayout(self.verticalLayout_27)
        self.verticalLayout_34.addLayout(self.horizontalLayout_15)
        self.line_6 = QtGui.QFrame(self.layoutWidget)
        self.line_6.setFrameShape(QtGui.QFrame.HLine)
        self.line_6.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_6.setObjectName(_fromUtf8("line_6"))
        self.verticalLayout_34.addWidget(self.line_6)
        self.horizontalLayout_17 = QtGui.QHBoxLayout()
        self.horizontalLayout_17.setObjectName(_fromUtf8("horizontalLayout_17"))
        self.verticalLayout_30 = QtGui.QVBoxLayout()
        self.verticalLayout_30.setObjectName(_fromUtf8("verticalLayout_30"))
        self.label_9 = QtGui.QLabel(self.layoutWidget)
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.verticalLayout_30.addWidget(self.label_9)
        self.horizontalLayout_10 = QtGui.QHBoxLayout()
        self.horizontalLayout_10.setObjectName(_fromUtf8("horizontalLayout_10"))
        self.verticalLayout_28 = QtGui.QVBoxLayout()
        self.verticalLayout_28.setObjectName(_fromUtf8("verticalLayout_28"))
        self.vL = QtGui.QLabel(self.layoutWidget)
        self.vL.setObjectName(_fromUtf8("vL"))
        self.verticalLayout_28.addWidget(self.vL)
        self.wL = QtGui.QLabel(self.layoutWidget)
        self.wL.setObjectName(_fromUtf8("wL"))
        self.verticalLayout_28.addWidget(self.wL)
        self.horizontalLayout_10.addLayout(self.verticalLayout_28)
        self.verticalLayout_29 = QtGui.QVBoxLayout()
        self.verticalLayout_29.setObjectName(_fromUtf8("verticalLayout_29"))
        self.vLE = QtGui.QLineEdit(self.layoutWidget)
        self.vLE.setObjectName(_fromUtf8("vLE"))
        self.verticalLayout_29.addWidget(self.vLE)
        self.wLE = QtGui.QLineEdit(self.layoutWidget)
        self.wLE.setText(_fromUtf8(""))
        self.wLE.setObjectName(_fromUtf8("wLE"))
        self.verticalLayout_29.addWidget(self.wLE)
        self.horizontalLayout_10.addLayout(self.verticalLayout_29)
        self.verticalLayout_30.addLayout(self.horizontalLayout_10)
        self.horizontalLayout_17.addLayout(self.verticalLayout_30)
        self.verticalLayout_33 = QtGui.QVBoxLayout()
        self.verticalLayout_33.setObjectName(_fromUtf8("verticalLayout_33"))
        self.label_10 = QtGui.QLabel(self.layoutWidget)
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.verticalLayout_33.addWidget(self.label_10)
        self.horizontalLayout_11 = QtGui.QHBoxLayout()
        self.horizontalLayout_11.setObjectName(_fromUtf8("horizontalLayout_11"))
        self.verticalLayout_31 = QtGui.QVBoxLayout()
        self.verticalLayout_31.setObjectName(_fromUtf8("verticalLayout_31"))
        self.xL = QtGui.QLabel(self.layoutWidget)
        self.xL.setObjectName(_fromUtf8("xL"))
        self.verticalLayout_31.addWidget(self.xL)
        self.yL = QtGui.QLabel(self.layoutWidget)
        self.yL.setObjectName(_fromUtf8("yL"))
        self.verticalLayout_31.addWidget(self.yL)
        self.horizontalLayout_11.addLayout(self.verticalLayout_31)
        self.verticalLayout_32 = QtGui.QVBoxLayout()
        self.verticalLayout_32.setObjectName(_fromUtf8("verticalLayout_32"))
        self.xLE = QtGui.QLineEdit(self.layoutWidget)
        self.xLE.setObjectName(_fromUtf8("xLE"))
        self.verticalLayout_32.addWidget(self.xLE)
        self.yLE = QtGui.QLineEdit(self.layoutWidget)
        self.yLE.setObjectName(_fromUtf8("yLE"))
        self.verticalLayout_32.addWidget(self.yLE)
        self.horizontalLayout_11.addLayout(self.verticalLayout_32)
        self.verticalLayout_33.addLayout(self.horizontalLayout_11)
        self.horizontalLayout_17.addLayout(self.verticalLayout_33)
        self.verticalLayout_34.addLayout(self.horizontalLayout_17)
        self.verticalLayout_35.addLayout(self.verticalLayout_34)
        self.horizontalLayout_18.addLayout(self.verticalLayout_35)
        self.gridLayout.addLayout(self.horizontalLayout_18, 1, 2, 2, 1)
        self.verticalLayout_17 = QtGui.QVBoxLayout()
        self.verticalLayout_17.setObjectName(_fromUtf8("verticalLayout_17"))
        self.label = QtGui.QLabel(self.layoutWidget)
        self.label.setObjectName(_fromUtf8("label"))
        self.verticalLayout_17.addWidget(self.label)
        self.verticalLayout_16 = QtGui.QVBoxLayout()
        self.verticalLayout_16.setObjectName(_fromUtf8("verticalLayout_16"))
        self.horizontalLayout_14 = QtGui.QHBoxLayout()
        self.horizontalLayout_14.setObjectName(_fromUtf8("horizontalLayout_14"))
        self.aL = QtGui.QLabel(self.layoutWidget)
        self.aL.setObjectName(_fromUtf8("aL"))
        self.horizontalLayout_14.addWidget(self.aL)
        self.aLE = QtGui.QLineEdit(self.layoutWidget)
        self.aLE.setObjectName(_fromUtf8("aLE"))
        self.horizontalLayout_14.addWidget(self.aLE)
        self.verticalLayout_16.addLayout(self.horizontalLayout_14)
        self.horizontalLayout_13 = QtGui.QHBoxLayout()
        self.horizontalLayout_13.setObjectName(_fromUtf8("horizontalLayout_13"))
        self.bL = QtGui.QLabel(self.layoutWidget)
        self.bL.setObjectName(_fromUtf8("bL"))
        self.horizontalLayout_13.addWidget(self.bL)
        self.bLE = QtGui.QLineEdit(self.layoutWidget)
        self.bLE.setObjectName(_fromUtf8("bLE"))
        self.horizontalLayout_13.addWidget(self.bLE)
        self.verticalLayout_16.addLayout(self.horizontalLayout_13)
        self.verticalLayout_17.addLayout(self.verticalLayout_16)
        self.gridLayout.addLayout(self.verticalLayout_17, 2, 0, 1, 1)
        spacerItem1 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem1, 2, 1, 1, 1)
        self.verticalLayout_37.addLayout(self.gridLayout)
        self.line_2 = QtGui.QFrame(self.layoutWidget)
        self.line_2.setFrameShape(QtGui.QFrame.HLine)
        self.line_2.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_2.setObjectName(_fromUtf8("line_2"))
        self.verticalLayout_37.addWidget(self.line_2)
        self.gridLayout_2.addLayout(self.verticalLayout_37, 0, 0, 1, 1)
        self.horizontalLayout_19 = QtGui.QHBoxLayout()
        self.horizontalLayout_19.setObjectName(_fromUtf8("horizontalLayout_19"))
        self.horizontalLayout_16 = QtGui.QHBoxLayout()
        self.horizontalLayout_16.setObjectName(_fromUtf8("horizontalLayout_16"))
        self.verticalLayout_4 = QtGui.QVBoxLayout()
        self.verticalLayout_4.setObjectName(_fromUtf8("verticalLayout_4"))
        self.chooseTemplateFileBN = QtGui.QPushButton(self.layoutWidget)
        self.chooseTemplateFileBN.setObjectName(_fromUtf8("chooseTemplateFileBN"))
        self.verticalLayout_4.addWidget(self.chooseTemplateFileBN)
        self.chooseSaveDirBN = QtGui.QPushButton(self.layoutWidget)
        self.chooseSaveDirBN.setObjectName(_fromUtf8("chooseSaveDirBN"))
        self.verticalLayout_4.addWidget(self.chooseSaveDirBN)
        self.horizontalLayout_16.addLayout(self.verticalLayout_4)
        self.verticalLayout_5 = QtGui.QVBoxLayout()
        self.verticalLayout_5.setObjectName(_fromUtf8("verticalLayout_5"))
        self.chooseTemplateFileLE = QtGui.QLineEdit(self.layoutWidget)
        self.chooseTemplateFileLE.setObjectName(_fromUtf8("chooseTemplateFileLE"))
        self.verticalLayout_5.addWidget(self.chooseTemplateFileLE)
        self.chooseSaveDirLE = QtGui.QLineEdit(self.layoutWidget)
        self.chooseSaveDirLE.setObjectName(_fromUtf8("chooseSaveDirLE"))
        self.verticalLayout_5.addWidget(self.chooseSaveDirLE)
        self.horizontalLayout_16.addLayout(self.verticalLayout_5)
        self.horizontalLayout_19.addLayout(self.horizontalLayout_16)
        spacerItem2 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_19.addItem(spacerItem2)
        self.verticalLayout_38 = QtGui.QVBoxLayout()
        self.verticalLayout_38.setObjectName(_fromUtf8("verticalLayout_38"))
        self.startBN = QtGui.QPushButton(self.layoutWidget)
        self.startBN.setObjectName(_fromUtf8("startBN"))
        self.verticalLayout_38.addWidget(self.startBN)
        self.clearBN = QtGui.QPushButton(self.layoutWidget)
        self.clearBN.setObjectName(_fromUtf8("clearBN"))
        self.verticalLayout_38.addWidget(self.clearBN)
        self.horizontalLayout_19.addLayout(self.verticalLayout_38)
        spacerItem3 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_19.addItem(spacerItem3)
        self.gridLayout_2.addLayout(self.horizontalLayout_19, 1, 0, 1, 1)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        Dialog.setWindowTitle(_translate("Dialog", "Dialog", None))
        self.label_2.setText(_translate("Dialog", "表头内容：", None))
        self.projectNameL.setText(_translate("Dialog", "工程名称：", None))
        self.checkRecordNoL.setText(_translate("Dialog", "检验记录编号：", None))
        self.checkNoL.setText(_translate("Dialog", "检验编号：", None))
        self.checkprojectL.setText(_translate("Dialog", "检验项目：", None))
        self.checkAccordL.setText(_translate("Dialog", "检验依据：", None))
        self.checkCountL.setText(_translate("Dialog", "检验数量：", None))
        self.piezometerNoL.setText(_translate("Dialog", "压力表表号：", None))
        self.dialgaugeNoL.setText(_translate("Dialog", "百分表表号：", None))
        self.loadL.setText(_translate("Dialog", "初始载荷：", None))
        self.label_3.setText(_translate("Dialog", "初始时间：", None))
        self.monthL.setText(_translate("Dialog", "月：", None))
        self.dayL.setText(_translate("Dialog", "日：", None))
        self.hourL.setText(_translate("Dialog", "时：", None))
        self.minuteL.setText(_translate("Dialog", "分：", None))
        self.label_4.setText(_translate("Dialog", "表一数据：", None))
        self.label_5.setText(_translate("Dialog", "1：", None))
        self.fL.setText(_translate("Dialog", "F：", None))
        self.gL.setText(_translate("Dialog", "G：", None))
        self.label_6.setText(_translate("Dialog", "2：", None))
        self.lL.setText(_translate("Dialog", "L：", None))
        self.mL.setText(_translate("Dialog", "M：", None))
        self.label_7.setText(_translate("Dialog", "3：", None))
        self.rL.setText(_translate("Dialog", "R：", None))
        self.sL.setText(_translate("Dialog", "S：", None))
        self.label_8.setText(_translate("Dialog", "4：", None))
        self.tL.setText(_translate("Dialog", "T：", None))
        self.uL.setText(_translate("Dialog", "U：", None))
        self.label_9.setText(_translate("Dialog", "5：", None))
        self.vL.setText(_translate("Dialog", "V：", None))
        self.wL.setText(_translate("Dialog", "W：", None))
        self.label_10.setText(_translate("Dialog", "6：", None))
        self.xL.setText(_translate("Dialog", "X：", None))
        self.yL.setText(_translate("Dialog", "Y：", None))
        self.label.setText(_translate("Dialog", "表格二数据：", None))
        self.aL.setText(_translate("Dialog", "a：", None))
        self.bL.setText(_translate("Dialog", "b：", None))
        self.chooseTemplateFileBN.setText(_translate("Dialog", "选择模板文件", None))
        self.chooseSaveDirBN.setText(_translate("Dialog", "选择文件生成目录", None))
        self.startBN.setText(_translate("Dialog", "开始生成", None))
        self.clearBN.setText(_translate("Dialog", "清除数据", None))

